#!/bin/sh
mvn clean package && docker build -t bhavikchavda/BusinessMSA .
docker rm -f BusinessMSA 2>/dev/null || true && docker run -it --name BusinessMSA -p 8080:8080 -p 4848:4848 -p 8181:8181 --name BusinessMSA bhavikchavda/BusinessMSA
