#!/bin/sh
mvn clean package && docker build -t bhavikchavda/DealShopFront .
docker rm -f DealShopFront 2>/dev/null || true && docker run -it --name DealShopFront -p 8080:8080 -p 4848:4848 -p 8181:8181 --name DealShopFront bhavikchavda/DealShopFront
