#!/bin/sh
mvn clean package && docker build -t bhavikchavda/CommonMSA .
docker rm -f CommonMSA 2>/dev/null || true && docker run -it --name CommonMSA -p 8080:8080 -p 4848:4848 -p 8181:8181 --name CommonMSA bhavikchavda/CommonMSA
