#!/bin/sh
mvn clean package && docker build -t bhavikchavda/UserMSA .
docker rm -f UserMSA 2>/dev/null || true && docker run -it --name UserMSA -p 8080:8080 -p 4848:4848 -p 8181:8181 --name UserMSA bhavikchavda/UserMSA
